name: C_C++_CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - clang-build

jobs:
  build-with-gcc:
    uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yaml@master
    with: 
      dependencies: 'gcc gcovr cmake openblas cblas lapacke scalapack boost eigen3 openmpi cppyy numpy libint'
      clang-build: false
      gcc-build: true
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}
  # build-with-clang:
  #   uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yaml@master
  #   with: 
  #     dependencies: 'clang gcovr cmake openblas cblas lapacke scalapack boost eigen3 openmpi cppyy numpy libint'
  #     clang-build: true
  #     gcc-build: false
  #   secrets:
  #     CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}