name: C_C++_CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cmake_version: [3.16.3]
        gcc_version: [9]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Get dependencies
        env:
          cmake_version: ${{ matrix.cmake_version }}
          gcc_version: ${{ matrix.gcc_version }}
        run: >
          .github/workflows/scripts/get_dependencies.sh gcc gcovr cmake ninja
          openblas cblas lapacke scalapack boost eigen3 openmpi cppyy numpy
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.1
        with:
          max-size: "1500M"
          key: ${{ matrix.cmake_version }}-${{ matrix.gcc_version }}
      - name: cache-libint
        id: cache
        uses: actions/cache@v2
        with:
          path: install
          key: libint-gcc${{ matrix.gcc_version }}
      - name: build-libint
        env:
          CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          export INSTALL_PATH=`pwd`/install
          # check code out
          wget https://github.com/evaleev/libint/releases/download/v2.6.0/libint-2.6.0.tgz
          tar -zxf libint-2.6.0.tgz
          cd libint-2.6.0
          export CXX=`which g++`
          export CC=`which gcc`
          ../cmake-3.16.3-Linux-x86_64/bin/cmake -H. -GNinja -Bbuild -DCMAKE_INSTALL_PREFIX=${INSTALL_PATH} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_FLAGS="-std=c++17" -DBUILD_SHARED_LIBS=ON -DCPP_GITHUB_TOKEN=$CPP_GITHUB_TOKEN
          cd build
          ninja
          ninja install
      - name: Build and test
        env:
          cmake_version: ${{ matrix.cmake_version }}
          gcc_version: ${{ matrix.gcc_version }}
          CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}
        run: .github/workflows/scripts/build_and_test.sh
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
