name: Build and Deploy Documentation
on:
  push:
    branches:
      - master
      - fix-doc

jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/deploy_docs_tmpl.yaml@master
    with: 
      target: nwchemex_cxx_api
      dependencies: cmake doxygen sphinx
